//
// Known-answer tests over the checked-in protocol vectors.
//
// The vectors exist so that iOS, Android, and relay-server can all assert the
// SAME fixed bytes and catch wire drift at build time rather than on a user's
// phone. This file is the reference consumer: it pins that the Node
// implementation — the one the desktop daemon actually ships — still satisfies
// them. ttyd_android/ and ttyd_mobile/ get their own consumers.
//
// If a test here fails, do NOT regenerate the vectors to make it pass. The
// vectors ARE the protocol; a diff in one is a breaking change to every
// already-paired device.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { computeSharedSecret, deriveKey, encrypt, decrypt } from './crypto.js';
import { unwrapSecret, wrapSecret } from './pairing-wrap.js';

interface Vectors {
  version: number;
  kdf: {
    info: string;
    salt: string;
    alicePrivate: string;
    alicePublic: string;
    bobPrivate: string;
    bobPublic: string;
    sharedSecret: string;
    derivedKey: string;
  };
  aeadDecrypt: Array<{ name: string; key: string; sealed: string; plaintext: string }>;
  pairingWrap: Array<{ name: string; token: string; wrapped: string; secret: string }>;
  clientFrames: Array<{ name: string; bytes: string; description: string }>;
}

const here = dirname(fileURLToPath(import.meta.url));
const vectors: Vectors = JSON.parse(
  readFileSync(join(here, '../../protocol-vectors/v1.json'), 'utf8'),
);

const b64 = (b: Buffer | Uint8Array) => Buffer.from(b).toString('base64');
const fromB64 = (s: string) => Buffer.from(s, 'base64');
const hex = (s: string) => fromB64(s).toString('hex');

// ── X25519 + HKDF ──────────────────────────────────────────────────────────
// The shared secret and derived key are what every byte on the wire depends on.
// If a port derives a different key, nothing decrypts, and the failure surfaces
// as a blank terminal rather than as a crypto error.

test('vectors: derives the pinned shared secret from Alice private + Bob public', () => {
  const shared = computeSharedSecret(fromB64(vectors.kdf.alicePrivate), fromB64(vectors.kdf.bobPublic));
  assert.equal(b64(shared), vectors.kdf.sharedSecret);
});

test('vectors: derives the same shared secret from the other side', () => {
  const shared = computeSharedSecret(fromB64(vectors.kdf.bobPrivate), fromB64(vectors.kdf.alicePublic));
  assert.equal(b64(shared), vectors.kdf.sharedSecret);
});

test('vectors: derives the pinned session key via HKDF-SHA256', () => {
  assert.equal(b64(deriveKey(fromB64(vectors.kdf.sharedSecret))), vectors.kdf.derivedKey);
});

test('vectors: pins the HKDF salt and info', () => {
  assert.equal(vectors.kdf.info, 'ttyd-relay-v1');
  assert.equal(vectors.kdf.salt, '');
});

// Anchors the vectors to an EXTERNAL standard. Without this the file would only
// prove we agree with ourselves — vectors generated by the same code that
// verifies them cannot catch a shared misunderstanding of X25519. These are
// RFC 7748 §6.1's published scalars and their published answers, so a port that
// passes is conformant, not merely consistent with us.
test('vectors: match the published RFC 7748 §6.1 known answers', () => {
  assert.equal(hex(vectors.kdf.alicePrivate),
    '77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a');
  assert.equal(hex(vectors.kdf.alicePublic),
    '8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a');
  assert.equal(hex(vectors.kdf.bobPrivate),
    '5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb');
  assert.equal(hex(vectors.kdf.bobPublic),
    'de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f');
  assert.equal(hex(vectors.kdf.sharedSecret),
    '4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742');
});

// ── AES-256-GCM ────────────────────────────────────────────────────────────
// THE porting hazard. CryptoKit's "combined" is nonce(12)||ciphertext||tag(16);
// Android's javax.crypto returns ciphertext||tag with the nonce carried
// separately. A port that concatenates in the wrong order still encrypts and
// decrypts happily against ITSELF, and fails only against the real relay.

for (const v of vectors.aeadDecrypt) {
  test(`vectors: decrypts the pinned sealed box (${v.name})`, () => {
    assert.equal(decrypt(fromB64(v.sealed), fromB64(v.key)).toString('utf8'), v.plaintext);
  });
}

test('vectors: sealed box is laid out nonce(12) || ciphertext || tag(16)', () => {
  for (const v of vectors.aeadDecrypt) {
    const sealed = fromB64(v.sealed);
    const plaintextLen = Buffer.from(v.plaintext, 'utf8').length;
    assert.equal(sealed.length, 12 + plaintextLen + 16, `${v.name} length`);
  }
});

test('vectors: AES-GCM round-trips its own output (nonce is random, so only the round-trip is fixed)', () => {
  const key = fromB64(vectors.kdf.derivedKey);
  assert.equal(decrypt(encrypt(Buffer.from('hello relay'), key), key).toString('utf8'), 'hello relay');
});

test('vectors: a tampered auth tag is rejected', () => {
  const v = vectors.aeadDecrypt[0];
  const sealed = fromB64(v.sealed);
  sealed[sealed.length - 1] ^= 0xff;
  assert.throws(() => decrypt(sealed, fromB64(v.key)));
});

// ── Pairing secret wrap ────────────────────────────────────────────────────
// Must match RelayCrypto.unwrapPairingSecret on the client. The relay never
// sees the pairing secret, so a mismatch here is invisible server-side.

for (const v of vectors.pairingWrap) {
  test(`vectors: unwraps the pinned wrapped secret (${v.name})`, () => {
    assert.equal(unwrapSecret(v.wrapped, v.token), v.secret);
  });
}

test('vectors: pairing wrap round-trips its own output', () => {
  assert.equal(unwrapSecret(wrapSecret('s3cret-value', 'tok-123'), 'tok-123'), 's3cret-value');
});

test('vectors: pairing wrap fails under the wrong token', () => {
  const v = vectors.pairingWrap[0];
  assert.throws(() => unwrapSecret(v.wrapped, `${v.token}-wrong`));
});

// ── Client frame layout ────────────────────────────────────────────────────
// The client↔relay link is [type:1][payload]; the inner termcast payload is
// [cmd:1][data]. These pin the constants so a port cannot invent its own.

test('vectors: pin the documented client frame bytes', () => {
  const byName = Object.fromEntries(vectors.clientFrames.map(f => [f.name, fromB64(f.bytes)]));

  assert.equal(byName['input_hello'][0], 0x30);
  assert.equal(byName['input_hello'].subarray(1).toString('utf8'), 'hello');

  assert.equal(byName['resize_80x24'][0], 0x31);
  assert.deepEqual(
    JSON.parse(byName['resize_80x24'].subarray(1).toString('utf8')),
    { columns: 80, rows: 24 },
  );

  // Outer relay frames carry the type in byte 0.
  assert.equal(byName['relay_handshake'][0], 0x01);
  assert.equal(byName['relay_data'][0], 0x03);
  assert.equal(byName['relay_ping'][0], 0x05);
  assert.equal(byName['relay_ping'].length, 1);
});

test('vectors: the relay_data frame decrypts to its inner termcast payload', () => {
  const byName = Object.fromEntries(vectors.clientFrames.map(f => [f.name, fromB64(f.bytes)]));
  const frame = byName['relay_data'];
  assert.equal(frame[0], 0x03);

  // [0x03] || AES-GCM combined(inner) — strip the outer type, then decrypt.
  const inner = decrypt(Buffer.from(frame.subarray(1)), fromB64(vectors.kdf.derivedKey));
  assert.equal(inner[0], 0x30); // inner termcast input command
  assert.equal(inner.subarray(1).toString('utf8'), 'hello');
});
