//
// Regenerates protocol-vectors/v1.json.
//
// Run only to ADD vectors, never to make a failing test pass: the vectors are
// the protocol, and changing an existing one is a breaking change to every
// already-paired device. `npm run vectors:check` (CI) fails if the committed
// file does not match what this script produces, so a drive-by edit to the JSON
// cannot land without also changing this generator.
//
// Everything here is deterministic. Nonces and keys are fixed constants, not
// randomBytes — a vector that changes per run is not a vector.
//
//   npx tsx scripts/generate-protocol-vectors.ts [--check]

import { createCipheriv, createPrivateKey, createPublicKey, hkdfSync } from 'node:crypto';
import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { computeSharedSecret, deriveKey } from '../src/crypto';

const X25519_PKCS8_PREFIX = Buffer.from('302e020100300506032b656e04220420', 'hex');

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../../protocol-vectors/v1.json');

const b64 = (b: Buffer | Uint8Array) => Buffer.from(b).toString('base64');

/** Raw 32-byte X25519 private key → raw 32-byte public key. */
function publicFromPrivate(privRaw: Buffer): Buffer {
  const priv = createPrivateKey({
    key: Buffer.concat([X25519_PKCS8_PREFIX, privRaw]),
    format: 'der',
    type: 'pkcs8',
  });
  const spki = createPublicKey(priv).export({ type: 'spki', format: 'der' });
  return Buffer.from(spki.subarray(-32));
}

/** AES-256-GCM with a FIXED nonce → nonce(12)||ciphertext||tag(16) ("combined"). */
function sealFixed(plaintext: string, key: Buffer, nonce: Buffer): Buffer {
  const cipher = createCipheriv('aes-256-gcm', key, nonce, { authTagLength: 16 });
  const ct = Buffer.concat([cipher.update(Buffer.from(plaintext, 'utf8')), cipher.final()]);
  return Buffer.concat([nonce, ct, cipher.getAuthTag()]);
}

function wrapFixed(secret: string, token: string, nonce: Buffer): string {
  const key = Buffer.from(
    hkdfSync('sha256', Buffer.from(token, 'utf8'),
      Buffer.from('termcast-pair-v1', 'utf8'),
      Buffer.from('pairing-secret-wrap', 'utf8'), 32),
  );
  return b64(sealFixed(secret, key, nonce));
}

function build(): unknown {
  // Fixed test scalars. Any 32 bytes is a valid X25519 private key (the
  // implementation clamps), so these are arbitrary but must never change.
  const alicePrivate = Buffer.from('77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a', 'hex');
  const bobPrivate = Buffer.from('5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb', 'hex');

  const alicePublic = publicFromPrivate(alicePrivate);
  const bobPublic = publicFromPrivate(bobPrivate);

  // Generated by the real implementation, then pinned. Both directions must
  // agree; the test asserts that separately.
  const sharedSecret = computeSharedSecret(alicePrivate, bobPublic);
  const derivedKey = deriveKey(sharedSecret);

  const nonceA = Buffer.from('000102030405060708090a0b', 'hex');
  const nonceB = Buffer.from('0b0a09080706050403020100', 'hex');

  const enc = (s: string) => Buffer.from(s, 'utf8');
  const frame = (type: number, rest: Buffer) => Buffer.concat([Buffer.from([type]), rest]);

  const handshakeJson = JSON.stringify({
    client_public_key: b64(alicePublic),
    phone_id: '00000000-0000-4000-8000-000000000000',
    paired_at: 1750000000000,
  });

  return {
    version: 1,
    _comment:
      'Shared protocol vectors for iOS, Android, and relay-server. Generated by ' +
      'relay-server/scripts/generate-protocol-vectors.ts. These bytes ARE the ' +
      'wire protocol: changing an existing vector breaks every paired device.',
    kdf: {
      algorithm: 'X25519 -> HKDF-SHA256 -> 32-byte AES key',
      info: 'ttyd-relay-v1',
      salt: '',
      alicePrivate: b64(alicePrivate),
      alicePublic: b64(alicePublic),
      bobPrivate: b64(bobPrivate),
      bobPublic: b64(bobPublic),
      sharedSecret: b64(sharedSecret),
      derivedKey: b64(derivedKey),
    },
    aeadDecrypt: [
      {
        name: 'short_ascii',
        key: b64(derivedKey),
        nonce: b64(nonceA),
        sealed: b64(sealFixed('hello relay', derivedKey, nonceA)),
        plaintext: 'hello relay',
      },
      {
        name: 'empty_plaintext',
        key: b64(derivedKey),
        nonce: b64(nonceB),
        sealed: b64(sealFixed('', derivedKey, nonceB)),
        plaintext: '',
      },
      {
        // Multi-byte UTF-8 catches a port that measures length in characters
        // rather than bytes.
        name: 'utf8_multibyte',
        key: b64(derivedKey),
        nonce: b64(nonceA),
        sealed: b64(sealFixed('héllo → 世界 🌍', derivedKey, nonceA)),
        plaintext: 'héllo → 世界 🌍',
      },
    ],
    pairingWrap: [
      {
        name: 'simple',
        token: 'tok-abc123',
        nonce: b64(nonceA),
        wrapped: wrapFixed('super-secret-pairing-value', 'tok-abc123', nonceA),
        secret: 'super-secret-pairing-value',
        salt: 'termcast-pair-v1',
        info: 'pairing-secret-wrap',
      },
    ],
    clientFrames: [
      {
        name: 'input_hello',
        description: 'inner termcast payload: 0x30 (input) || utf8 bytes',
        bytes: b64(frame(0x30, enc('hello'))),
      },
      {
        name: 'resize_80x24',
        description: 'inner termcast payload: 0x31 (resize) || JSON {columns,rows}',
        bytes: b64(frame(0x31, enc(JSON.stringify({ columns: 80, rows: 24 })))),
      },
      {
        name: 'relay_handshake',
        description: 'outer client->relay frame: 0x01 || JSON {client_public_key, phone_id, paired_at}',
        bytes: b64(frame(0x01, enc(handshakeJson))),
      },
      {
        name: 'relay_data',
        description: 'outer client->relay frame: 0x03 || AES-GCM combined(inner payload)',
        bytes: b64(frame(0x03, sealFixed('\x30hello', derivedKey, nonceA))),
      },
      {
        name: 'relay_ping',
        description: 'outer client->relay frame: 0x05, no payload',
        bytes: b64(Buffer.from([0x05])),
      },
    ],
  };
}

const json = `${JSON.stringify(build(), null, 2)}\n`;

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== json) {
    console.error(
      'protocol-vectors/v1.json is out of sync with the generator.\n' +
      'If you INTENDED to change the wire protocol, re-run without --check and ' +
      'understand that every already-paired device breaks.',
    );
    process.exit(1);
  }
  console.log('protocol vectors match the generator.');
} else {
  writeFileSync(OUT, json);
  console.log(`wrote ${OUT}`);
}
